name: showings
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev
publish_to: 'none'

version: 1.0.2+5

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.12.2
  sliding_up_panel: ^2.0.0+1
  cached_network_image: ^3.4.1
  webview_flutter: ^4.13.0
  geolocator: ^9.0.2
  csv: ^5.0.2
  geocoding: ^2.1.0
  shimmer: ^3.0.0
  image_picker: ^1.0.4
  permission_handler: ^11.0.1
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  xml: ^6.3.0
  charset_converter: ^2.0.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  photo_view: ^0.14.0
  url_launcher: ^6.3.1
  http_parser: ^4.0.2
  flutter_image_compress: ^2.1.0
  path_provider: ^2.1.1
  intl: ^0.19.0

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/play_store_512.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/example.png
    - assets/images/example2.jpg
    - assets/images/spring_d.png
    - assets/images/spring_marker.png
    - assets/images/hooded_crane.jpg
    - assets/images/p5.png
    - assets/data/codes.csv
    - assets/images/naver_login.png
    - assets/images/kakao_login.png
    - assets/images/make_group.png
    - assets/images/login_background.png
